# Generated by Django 2.2.3 on 2020-03-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('time', models.DurationField()),
                ('price', models.FloatField(default=300)),
                ('team_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('time', models.DurationField()),
                ('coach', models.CharField(max_length=250)),
                ('turf', models.IntegerField(default=1)),
                ('coaching_span', models.CharField(choices=[('ONE MONTH', '1 month'), ('THREE MONTHS', '3 months'), ('SIX MONTHS', '6 months'), ('ONE YEAR', '1 year')], default='ONE MONTH', max_length=15)),
                ('fees', models.FloatField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('address', models.TextField(max_length=500)),
                ('phone_no', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('game', models.ManyToManyField(to='app1.Coaching')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
